remote_theme: just-the-docs/just-the-docs

title: 살가이
description: 독거노인을 위한 AI 복약관리 프로젝트
logo: "/assets/images/살가이.png"

plugins:
  - jekyll-remote-theme
  
url: https://salguy.github.io

search_enabled: false

aux_links:
  "살가이 GitHub 페이지": "//github.com/salguy"
aux_links_new_tab: true

# 사이드바 설정
collections:
  docs:
    output: true
    permalink: /:collection/:path/
    sort_by: nav_order
    
defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: default

just_the_docs:
  collections:
    docs:
      name: 문서
      nav_order: 1
      nav_fold: true

footer_content: "Copyright &copy; 2025 Salguy Project. All rights reserved."
